# Testing the EM-EDX classs and basic usage of the methods
- An EM-EDX pair are saved in the EM-EDX class.
- Preprocessing methods are tracked in the class instance.

In [2]:
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from utils_EDX import *
import numpy as np
import hyperspy.api as hs
import os
import matplotlib.pyplot as plt
import copy
from importlib import reload
from EDX import *
%load_ext autoreload
%autoreload 2

### Define an EM-EDX instance

In [4]:
# load data
file_path = "../data/EMD/EDXdataset.emd"
EDX, haadf, xray_energies = load_EDX(file_path, first_frame=None, last_frame=3,sum_frames=True)

WARNING | RosettaSciIO | The file contains only one spectrum stream (rsciio.emd._emd_velox:590)

In [7]:
# define an instance and apply preprocessing (copy_instance defaults to false)
tile = EM_EDX(haadf, EDX, xray_energies)
tile = tile.apply("crop", parameters = {"crop_idx": (0,1000,0,1000,0,1000)}, notes='first operation')

# summary
tile.summary()

,operation,parameters,haadf size,EDX size,notes
0,crop,"crop_idx=(0, 1000, 0, 1000, 0, 1000)","(1000, 1000)","(1000, 1000, 1000)",first operation

#### copy_instance set to True to define a new EM-EDX instnce (while preserving the memory of the old one)

In [8]:
tile2 = tile.apply("crop", parameters={"crop_idx": (slice(0,100),slice(0,200),slice(0,1000,10))},copy_instance=True)
tile2.summary()

,operation,parameters,haadf size,EDX size,notes
0,crop,"crop_idx=(0, 1000, 0, 1000, 0, 1000)","(1000, 1000)","(1000, 1000, 1000)",first operation
1,crop,"crop_idx=(slice(0, 100, None), slice(0, 200, N...","(100, 200)","(100, 200, 100)",None